version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-s3-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1p6shb36vi794"
s3_prefix = "sam-s3-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
